/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2015-05-31 14:15:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import java.net.*;
import itm.image.*;
import itm.model.*;
import itm.util.*;
import javax.imageio.*;
import java.awt.*;
import java.awt.image.*;

public final class tags_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("/*******************************************************************************\r\n");
      out.write(" This file is part of the WM.II.ITM course 2014\r\n");
      out.write(" (c) University of Vienna 2009-2014\r\n");
      out.write(" *******************************************************************************/\r\n");
      out.write("-->\r\n");

       

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        fill in your code here :)\r\n");
      out.write("        ");

        
            String tag = null;

            // ***************************************************************
            //  Fill in your code here!
            // ***************************************************************

            // get "tag" parameter   
            if(request.getParameter("tag")!=null){
            tag = request.getParameter("tag"); }
            
            // if no param was passed, forward to index.jsp (using jsp:forward)
			if(request.getParameter("tag")==null){ 
      if (true) {
        _jspx_page_context.forward("index.jsp");
        return;
      }
      out.write(" \r\n");
      out.write("        ");
 }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h1>Media that is tagged with ");
      out.print( tag );
      out.write("</h1>\r\n");
      out.write("        <a href=\"index.jsp\">back</a>\r\n");
      out.write("\r\n");
      out.write("        ");


            // ***************************************************************
            //  Fill in your code here!
            // ***************************************************************
        	ArrayList<AbstractMedia> media = MediaFactory.getMedia(tag);
        
            // get all media objects that are tagged with the passed tag
            for ( AbstractMedia medium : media ) {
      out.write("\r\n");
      out.write("            <div style=\"width:300px;height:300px;padding:10px;float:left;\">\r\n");
      out.write("        ");

    
        // handle images
        if ( medium instanceof ImageMedia ) {
        	// display image thumbnail and metadata
            ImageMedia img = (ImageMedia) medium;
        	 
            
      out.write("\r\n");
      out.write("            <div style=\"width:200px;height:200px;padding:10px;\">\r\n");
      out.write("                <a href=\"media/img/");
      out.print( img.getInstance().getName());
      out.write("\">\r\n");
      out.write("                <img onmouseover=\"this.src='media/md/");
      out.print( img.getInstance().getName() );
      out.write(".hist.png'; \" onmouseout=\"this.src='media/md/");
      out.print( img.getInstance().getName() );
      out.write(".thumb.png';\" src=\"media/md/");
      out.print( img.getInstance().getName() );
      out.write(".thumb.png\" border=\"0\" height=\"200px\" width=\"200px\"/>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                Name: ");
      out.print( img.getName() );
      out.write("<br/>\r\n");
      out.write("                Dimensions: ");
      out.print( img.getWidht() );
      out.write('x');
      out.print( img.getHeight() );
      out.write("px<br/>\r\n");
      out.write("                Tags: ");
 for ( String t : img.getTags() ) { 
      out.write("<a href=\"tags.jsp?tag=");
      out.print( t );
      out.write('"');
      out.write('>');
      out.print( t );
      out.write("</a> ");
 } 
      out.write("<br/>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
  
            }	
        
            // iterate over all available media objects and display them
        }
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
